version: "3.9"
services:
  gitlab:
    image: gitlab/gitlab-ce:latest
    restart: always
    hostname: gitlab-ce
    container_name: gitlab-ce
    environment:
      GITLAB_OMNIBUS_CONFIG: |
        external_url 'http://gitlab-ce'
    ports:
      - 80:80
      - 443:443
      - 22:22
    volumes:
      - wssdevsecops-config:/etc/gitlab
      - wssdevsecops-logs:/var/log/gitlab
      - wssdevsecops-data:/var/opt/gitlab
    shm_size: '256m'
    networks:
      - devsecops
  sonardb:
    image: postgres:12
    hostname: postgresql
    container_name: postgresql
    environment:
      POSTGRES_USER: sonar
      POSTGRES_PASSWORD: sonar
      POSTGRES_DB: sonar
    volumes:
      - wssdevsecops-postgresql:/var/lib/postgresql
      - wssdevsecops-postgresql_data:/var/lib/postgresql/data
    networks:
      - devsecops
  sonarqube:
    image: sonarqube:community
    hostname: sonarqube
    container_name: sonarqube
    depends_on:
      - sonardb
    environment:
      SONAR_JDBC_URL: jdbc:postgresql://sonardb:5432/sonar
      SONAR_JDBC_USERNAME: sonar
      SONAR_JDBC_PASSWORD: sonar
    volumes:
      - wssdevsecops-sonarqube_data:/opt/sonarqube/data
      - wssdevsecops-sonarqube_extensions:/opt/sonarqube/extensions
      - wssdevsecops-sonarqube_logs:/opt/sonarqube/logs
    ports:
      - 9000:9000
    networks:
      - devsecops
  mysql:
    image: mysql:5.5
    volumes:
      - wssdevsecops-mysql:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: ec95c258266b8e985848cae688effa2b
    networks:
      - devsecops
  dvja:
    build: ./dvja
    depends_on:
      - mysql
    ports:
      - 8088:8080
    environment:
      MYSQL_USER: root
      MYSQL_PASSWORD: ec95c258266b8e985848cae688effa2b
    networks:
      - devsecops

networks:
  devsecops:
    name: devsecops-network

volumes:
  wssdevsecops-config:
  wssdevsecops-logs:
  wssdevsecops-data:
  wssdevsecops-sonarqube_data:
  wssdevsecops-sonarqube_extensions:
  wssdevsecops-sonarqube_logs:
  wssdevsecops-postgresql:
  wssdevsecops-postgresql_data:
  wssdevsecops-mysql: