version: "3.9"
services:
  gitlab-runner:
    image: gitlab/gitlab-runner:alpine
    container_name: gitlab-runner    
    restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - wssdevsecops-gitlab-runner:/etc/gitlab-runner
      - wssdevsecops-gitlab-runner:/home/gitlab-runner

volumes:
  wssdevsecops-gitlab-runner: